server:
  port: 9192
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://be0yjsye8cfeybgxwnrq-mysql.services.clever-cloud.com:3306/be0yjsye8cfeybgxwnrq
    username: uuwbg3phobhdxshx
    password: QD7ebmHJ0DGkYKeUMbNn
  jpa:
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: 'true'
  application:
    name: USER-SERVICE
